function ajaxRequestValidator(input) {
    let methodRegex = new RegExp(/^Method: (GET|POST|PUT|DELETE)$/, 'g');
    let credentialsRegex = new RegExp(/^Credentials: (Basic|Bearer) [A-Za-z0-9]+$/, 'g');
    let contentRegex = new RegExp(/^Content: [A-Za-z0-9.]+$/, 'g');
    let hashPattern = input.pop();

    for (let i = 0; i < input.length - 1; i += 3) {
        let method = input[i].match(methodRegex);
        let credentials = input[i + 1].match(credentialsRegex);
        let content = input[i + 2].match(contentRegex);

        if (method === null || credentials === null || content === null) {
            console.log('Response-Code:400');
            continue;
        }
        else {
            method = method[0].split(' ')[1];
            credentials = credentials[0].split(' ');
        }

        if (credentials[1] === 'Basic' && (method === 'POST' || method === 'PUT' || method === 'DELETE')) {
            console.log(`Response-Method:${method}&Code:401`);
        }
        else {
            let check = true;
            let re = new RegExp(/([0-9])([A-Za-z])/, 'g');

            let match;
            while (match = re.exec(hashPattern)) {
                let repeating = Number(match[1]);
                let letter = match[2].toLowerCase();
                let reCount = new RegExp(letter, 'g');
                let count = 0;
                let innerMatch = credentials[2].match(reCount);
                if (innerMatch !== null) {
                    count = innerMatch.length;
                }
                else {
                    check = false;
                }

                if (count === repeating) {
                    check = true;
                    break;
                }
                else {
                    check = false;
                }
            }

            if (!check) {
                console.log(`Response-Method:${method}&Code:403`);
            }
            else {
                console.log(`Response-Method:${method}&Code:200&Header:${credentials[2]}`);
            }
        }
    }
}

// ajaxRequestValidator(
//     'Method: DELETE',
// 'Credentials: Basic akfjhiaumdgh9nnqdpppasdasd5m9382dnn23pp',
// 'Content: password',
// 'Method: DELETE',
// 'Credentials: Bearer thefoo492389sssasdkajgvkjmuneypp',
// 'Content: this.is.sparta',
// 'Method: PUT',
// 'Credentials: Bearer 1982361873oo5371982361873oo537',
// 'Content: Admin',
// 'Method: DELETE',
// 'Credentials: Bearer 193857918oo365813thefoo492389sss',
// 'Content: this.is.sparta',
// 'Method: GET',
// 'Credentials: Basic thef58823esoasdkajgvkjmuneypp',
// 'Content: watafak',
// 'Method: POST',
// 'Credentials: Bearer gkj39883m9278wenfypppasdasd5m9382dnn23pp',
// 'Content: Spartaaaa',
// 'Method: DELETE',
// 'Credentials: Bearer 1982361873oo537gkj39883m9278wenfyppp',
// 'Content: password',
// 'Method: GET',
// 'Credentials: Bearer thef58823esothefoo492389sss',
// 'Content: username',
// 'Method: POST',
// 'Credentials: Basic 1982361873oo537gkj39883m9278wenfyppp',
// 'Content: username',
// 'Method: GET',
// 'Credentials: Bearer gkj39883m9278wenfypppasdasd5m9382dnn23pp',
// 'Content: invalid_input',
// 'Method: GET',
// 'Credentials: Bearer gkj39883m9278wenfypppthef58823eso',
// 'Content: Admin',
// 'Method: POST',
// 'Credentials: Basic gkj39883m9278wenfypppasdkajgvkjmuneypp',
// 'Content: and*more',
// 'Method: DELETE',
// 'Credentials: Basic 193857918oo365813gkj39883m9278wenfyppp',
// 'Content: to.dungeons.deep',
// 'Method: GET',
// 'Credentials: Bearer thefoo492389sssasdasd5m9382dnn23pp',
// 'Content: Best.Content.Ever',
// 'Method: GET',
// 'Credentials: Basic 1982361873oo537thef58823eso',
// 'Content: Best.Content.Ever',
// 'Method: DELETE',
// 'Credentials: Basic asdasd5m9382dnn23ppasdasd5m9382dnn23pp',
// 'Content: Bleblablu',
// 'Method: DELETE',
// 'Credentials: Bearer 193857918oo365813akfjhiaumdgh9nnqdppp',
// 'Content: Admin',
// 'Method: DELETE',
// 'Credentials: Bearer gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
// 'Content: the.73l37U8135',
// 'Method: DELETE',
// 'Credentials: Bearer gkj39883m9278wenfypppgkj39883m9278wenfyppp',
// 'Content: the.73l37U8135',
// 'Method: POST',
// 'Credentials: Basic asdasd5m9382dnn23pp1982361873oo537',
// 'Content: watafak',
// 'Method: POST',
// 'Credentials: Bearer asdkajgvkjmuneyppasdkajgvkjmuneypp',
// 'Content: 2pac3pac4pac5',
// 'Method: GET',
// 'Credentials: Bearer asdkajgvkjmuneyppthefoo492389sss',
// 'Content: Best.Content.Ever',
// 'Method: GET',
// 'Credentials: Bearer 193857918oo365813akfjhiaumdgh9nnqdppp',
// 'Content: Aaaaalelujaaah',
// 'Method: POST',
// 'Credentials: Basic 1982361873oo537193857918oo365813',
// 'Content: Bleblablu',
// 'Method: PUT',
// 'Credentials: Bearer asdkajgvkjmuneyppthefoo492389sss',
// 'Content: dragons',
// 'Method: PUT',
// 'Credentials: Basic 1982361873oo537asdasd5m9382dnn23pp',
// 'Content: and.caverns.old',
// 'Method: GET',
// 'Credentials: Bearer thefoo492389sssgkj39883m9278wenfyppp',
// 'Content: Aaaaalelujaaah',
// 'Method: POST',
// 'Credentials: Basic thefoo492389sssasdasd5m9382dnn23pp',
// 'Content: this.is.sparta',
// 'Method: DELETE',
// 'Credentials: Basic akfjhiaumdgh9nnqdpppasdasd5m9382dnn23pp',
// 'Content: dragons',
// 'Method: GET',
// 'Credentials: Basic 193857918oo3658131982361873oo537',
// 'Content: 2pac3pac4pac5',
// 'Method: DELETE',
// 'Credentials: Basic thefoo492389sssthefoo492389sss',
// 'Content: Best.Content.Ever',
// 'Method: POST',
// 'Credentials: Bearer thefoo492389sssakfjhiaumdgh9nnqdppp',
// 'Content: this.is.sparta',
// 'Method: DELETE',
// 'Credentials: Bearer asdasd5m9382dnn23ppthef58823eso',
// 'Content: televisionControll',
// 'Method: PUT',
// 'Credentials: Bearer 193857918oo365813thef58823eso',
// 'Content: watafak',
// 'Method: PUT',
// 'Credentials: Basic 1982361873oo537akfjhiaumdgh9nnqdppp',
// 'Content: password',
// 'Method: GET',
// 'Credentials: Basic thef58823esothefoo492389sss',
// 'Content: Bleblablu',
// 'Method: POST',
// 'Credentials: Basic thef58823esothef58823eso',
// 'Content: more-invalid-input',
// 'Method: DELETE',
// 'Credentials: Basic thefoo492389sssasdkajgvkjmuneypp',
// 'Content: Aaaaalelujaaah',
// 'Method: POST',
// 'Credentials: Basic asdasd5m9382dnn23ppasdasd5m9382dnn23pp',
// 'Content: Spartaaaa',
// 'Method: GET',
// 'Credentials: Basic 193857918oo365813asdkajgvkjmuneypp',
// 'Content: 12398dsasd',
// 'Method: DELETE',
// 'Credentials: Basic akfjhiaumdgh9nnqdpppthefoo492389sss',
// 'Content: 12398dsasd',
// 'Method: GET',
// 'Credentials: Basic asdkajgvkjmuneyppasdkajgvkjmuneypp',
// 'Content: watafak',
// 'Method: PUT',
// 'Credentials: Basic asdkajgvkjmuneypp193857918oo365813',
// 'Content: The.misty.mountains.cold',
// 'Method: GET',
// 'Credentials: Bearer akfjhiaumdgh9nnqdpppgkj39883m9278wenfyppp',
// 'Content: Admin',
// 'Method: POST',
// 'Credentials: Bearer thef58823esoasdkajgvkjmuneypp',
// 'Content: watafak',
// 'Method: POST',
// 'Credentials: Bearer thef58823esoakfjhiaumdgh9nnqdppp',
// 'Content: to.dungeons.deep',
// 'Method: POST',
// 'Credentials: Bearer thefoo492389sssthefoo492389sss',
// 'Content: to.dungeons.deep',
// 'Method: POST',
// 'Credentials: Bearer akfjhiaumdgh9nnqdpppakfjhiaumdgh9nnqdppp',
// 'Content: this.is.sparta',
// 'Method: DELETE',
// 'Credentials: Basic akfjhiaumdgh9nnqdppp193857918oo365813',
// 'Content: Aaaaalelujaaah',
// 'Method: DELETE',
// 'Credentials: Bearer 193857918oo365813akfjhiaumdgh9nnqdppp',
// 'Content: demons',
// 'Method: PUT',
// 'Credentials: Bearer gkj39883m9278wenfypppasdkajgvkjmuneypp',
// 'Content: to.dungeons.deep',
// '2m5p3n3o'
// )

ajaxRequestValidator(['Method: GET',
'Credentials: Basic fadf9qu8ue9q9dajifffffff',
'Content: 11111845111111.mnogo.gaden.test',
'Method: POST',
'Credentials: Bearer thpefoo492389sssasdkajgvkjmuneyp',
'Content: basi.mnogo.gaden.test',
'Method: PUT',
'Credentials: Bearer akfjhiaumdgh9nnqdpppasdasd5m9382dnnoo23pp',
'Content: mnogo.gaden.test',
'Method: DELETE',
'Credentials: Bearer thefoo492389sssasdkajgvkjmuney',
'Content: gaden.test',
'0p']);

// ajaxRequestValidator(['Method: GET',
//     'Credentials: Basic gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
//     'Content: and*more',
//     'Method: GET',
//     'Credentials: Bearer asdasd5m9382dnn23ppasdkajgvkjmuneypp',
//     'Content: and*more',
//     'Method: PUT',
//     'Credentials: Basic asdkajgvkjmuneyppasdasd5m9382dnn23pp',
//     'Content: password',
//     'Method: POST',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppakfjhiaumdgh9nnqdppp',
//     'Content: this.is.sparta',
//     'Method: DELETE',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppgkj39883m9278wenfyppp',
//     'Content: Spartaaaa',
//     'Method: DELETE',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppgkj39883m9278wenfyppp',
//     'Content:  username',
//     'Method: DELET E',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppgkj39883m9278wenfyppp',
//     'Content: more-invalid-input',
//     'Method: DELETE',
//     'Credentials: Bearer gkj39883m9278wenfypppasdkajgvkjmuneypp',
//     'Content: this.is.sparta',
//     'Method: DELETE',
//     'Credentials: Basic asdkajgvkjmuneyppakfjhiaumdgh9nnqdppp',
//     'Content: invalid_input',
//     'Method: GET',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppasdasd5m9382dnn23pp',
//     'Content: som eshit',
//     'Method: PUT',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppasdkajgvkjmuneypp',
//     'Content: this.is.sparta',
//     'Method: GET',
//     'Credentials: Basic gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
//     'Content: watafa k',
//     'Method: GET',
//     'Credentials: Bearer gkj39883m9278wenfypppgkj39883m9278wenfyppp',
//     'Content: televisionControll',
//     'Method: DELETE',
//     'Credentials: Basic asdkajgvkjmuneyppakfjhiaumdgh9nnqdppp',
//     'Content: this.is.sparta',
//     'Method: POST',
//     'Credentials: Basic gkj39883m9278wenfypppasdkajgvkjmuneypp',
//     'Content: 12398dsasd',
//     'Method: PUT',
//     'Credentials: Bearer gkj39883m9278wenfypppgkj39883m9278wenfyppp',
//     'Content: Admin',
//     'Method: GET',
//     'Credentials: Basic asdkajgvkjmuneyppasdasd5m9382dnn23pp',
//     'Content: someshit',
//     'Method: POST',
//     'Credentials: Bearer gkj39883m9278wenfypppgkj39883m9278wenfyppp',
//     'Content: username',
//     'Method: PUT',
//     'Credentials: Basic asdasd5m9382dnn23ppakfjhiaumdgh9nnqdppp',
//     'Content: invalid_input',
//     'Method: GET',
//     'Credentials: Basic asdasd5m9382dnn23ppgkj39883m9278wenfyppp',
//     'Content: username',
//     'Method: POST',
//     'Credentials: Bearer asdasd5m9382dnn23ppasdasd5m9382dnn23pp',
//     'Content: username',
//     'Method: PUT',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppasdasd5m9382dnn23pp',
//     'Content: someshit',
//     'Method: DELETE',
//     'Credentials: Bearer asdkajgvkjmuneyppgkj39883m9278wenfyppp',
//     'Content: watafak',
//     'Method: PUT',
//     'Credentials: Bearer asdasd5m9382dnn23ppakfjhiaumdgh9nnqdppp',
//     'Content: password',
//     'Method: PUT',
//     'Credentials: Bearer gkj39883m9278wenfypppgkj39883m9278wenfyppp',
//     'Content: Spartaaaa',
//     'Method: GET',
//     'Credentials: Basic asdkajgvkjmuneyppasdasd5m9382dnn23pp',
//     'Content: Admin',
//     'Method: DELETE',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppakfjhiaumdgh9nnqdppp',
//     'Content: 12398dsasd',
//     'Method: POST',
//     'Credentials: Bearer asdasd5m9382dnn23ppakfjhiaumdgh9nnqdppp',
//     'Content: invalid_input',
//     'Method: GET',
//     'Credentials: Basic gkj39883m9278wenfypppgkj39883m9278wenfyppp',
//     'Content: someshit',
//     'Method: PUT',
//     'Credentials: Basic asdkajgvkjmuneyppasdasd5m9382dnn23pp',
//     'Content: someshit',
//     'Method: GET',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppasdkajgvkjmuneypp',
//     'Content: and*more',
//     'Method: POST',
//     'Credentials: Bearer asdasd5m9382dnn23ppgkj39883m9278wenfyppp',
//     'Content: this.is.sparta',
//     'Method: PUT',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppasdkajgvkjmuneypp',
//     'Content: and*more',
//     'Method: PUT',
//     'Credentials: Bearer gkj39883m9278wenfypppgkj39883m9278wenfyppp',
//     'Content: this.is.sparta',
//     'Method: PUT',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppakfjhiaumdgh9nnqdppp',
//     'Content: username',
//     'Method: PUT',
//     'Credentials: Bearer asdkajgvkjmuneyppasdasd5m9382dnn23pp',
//     'Content: invalid_input',
//     'Method: DELETE',
//     'Credentials: Bearer gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
//     'Content: Spartaaaa',
//     'Method: POST',
//     'Credentials: Basic gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
//     'Content: password',
//     'Method: GET',
//     'Credentials: Basic asdasd5m9382dnn23ppakfjhiaumdgh9nnqdppp',
//     'Content: Admin',
//     'Method: DELETE',
//     'Credentials: Basic asdasd5m9382dnn23ppakfjhiaumdgh9nnqdppp',
//     'Content: username',
//     'Method: POST',
//     'Credentials: Basic asdkajgvkjmuneyppasdkajgvkjmuneypp',
//     'Content: 12398dsasd',
//     'Method: GET',
//     'Credentials: Bearer asdasd5m9382dnn23ppasdkajgvkjmuneypp',
//     'Content: this.is.sparta',
//     'Method: POST',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppakfjhiaumdgh9nnqdppp',
//     'Content: and*more',
//     'Method: POST',
//     'Credentials: Basic asdasd5m9382dnn23ppasdkajgvkjmuneypp',
//     'Content: the.73l37U8135',
//     'Method: DELETE',
//     'Credentials: Basic asdasd5m9382dnn23ppasdasd5m9382dnn23pp',
//     'Content: username',
//     'Method: POST',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppasdasd5m9382dnn23pp',
//     'Content: and*more',
//     'Method: POST',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppasdasd5m9382dnn23pp',
//     'Content: 12398dsasd',
//     'Method: DELETE',
//     'Credentials: Bearer gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
//     'Content: Spartaaaa',
//     'Method: GET',
//     'Credentials: Bearer gkj39883m9278wenfypppasdasd5m9382dnn23pp',
//     'Content: password',
//     'Method: POST',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppgkj39883m9278wenfyppp',
//     'Content: and*more',
//     'Method: DELETE',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppakfjhiaumdgh9nnqdppp',
//     'Content: and*more',
//     'Method: DELETE',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppasdkajgvkjmuneypp',
//     'Content: more-invalid-input',
//     'Method: DELETE',
//     'Credentials: Bearer gkj39883m9278wenfypppasdasd5m9382dnn23pp',
//     'Content: invalid_input',
//     'Method: PUT',
//     'Credentials: Basic asdasd5m9382dnn23ppasdkajgvkjmuneypp',
//     'Content: watafak',
//     'Method: PUT',
//     'Credentials: Basic asdkajgvkjmuneyppakfjhiaumdgh9nnqdppp',
//     'Content: password',
//     'Method: POST',
//     'Credentials: Bearer asdkajgvkjmuneyppgkj39883m9278wenfyppp',
//     'Content: and*more',
//     'Method: GET',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppasdasd5m9382dnn23pp',
//     'Content: this.is.sparta',
//     'Method: POST',
//     'Credentials: Bearer asdasd5m9382dnn23ppasdasd5m9382dnn23pp',
//     'Content: more-invalid-input',
//     'Method: POST',
//     'Credentials: Basic asdasd5m9382dnn23ppakfjhiaumdgh9nnqdppp',
//     'Content: 12398dsasd',
//     'Method: GET',
//     'Credentials: Bearer asdkajgvkjmuneyppasdasd5m9382dnn23pp',
//     'Content: password',
//     'Method: DELETE',
//     'Credentials: Bearer asdkajgvkjmuneyppasdkajgvkjmuneypp',
//     'Content: this.is.sparta',
//     'Method: DELETE',
//     'Credentials: Bearer asdasd5m9382dnn23ppakfjhiaumdgh9nnqdppp',
//     'Content: 12398dsasd',
//     'Method: GET',
//     'Credentials: Bearer asdkajgvkjmuneyppgkj39883m9278wenfyppp',
//     'Content: watafak',
//     'Method: POST',
//     'Credentials: Bearer gkj39883m9278wenfypppasdasd5m9382dnn23pp',
//     'Content: password',
//     'Method: PUT',
//     'Credentials: Bearer asdasd5m9382dnn23ppasdasd5m9382dnn23pp',
//     'Content: more-invalid-input',
//     'Method: DELETE',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppgkj39883m9278wenfyppp',
//     'Content: televisionControll',
//     'Method: PUT',
//     'Credentials: Bearer gkj39883m9278wenfypppasdasd5m9382dnn23pp',
//     'Content: the.73l37U8135',
//     'Method: PUT',
//     'Credentials: Basic asdasd5m9382dnn23ppakfjhiaumdgh9nnqdppp',
//     'Content: 12398dsasd',
//     'Method: GET',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppasdasd5m9382dnn23pp',
//     'Content: 12398dsasd',
//     'Method: DELETE',
//     'Credentials: Basic gkj39883m9278wenfypppasdasd5m9382dnn23pp',
//     'Content: this.is.sparta',
//     'Method: PUT',
//     'Credentials: Bearer asdasd5m9382dnn23ppakfjhiaumdgh9nnqdppp',
//     'Content: this.is.sparta',
//     'Method: PUT',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppasdasd5m9382dnn23pp',
//     'Content: this.is.sparta',
//     'Method: PUT',
//     'Credentials: Bearer asdasd5m9382dnn23ppasdasd5m9382dnn23pp',
//     'Content: invalid_input',
//     'Method: PUT',
//     'Credentials: Basic asdasd5m9382dnn23ppasdasd5m9382dnn23pp',
//     'Content: Admin',
//     'Method: GET',
//     'Credentials: Bearer asdkajgvkjmuneyppasdkajgvkjmuneypp',
//     'Content: this.is.sparta',
//     'Method: PUT',
//     'Credentials: Bearer gkj39883m9278wenfypppgkj39883m9278wenfyppp',
//     'Content: someshit',
//     'Method: GET',
//     'Credentials: Bearer asdkajgvkjmuneyppgkj39883m9278wenfyppp',
//     'Content: Spartaaaa',
//     'Method: POST',
//     'Credentials: Bearer gkj39883m9278wenfypppasdkajgvkjmuneypp',
//     'Content: invalid_input',
//     'Method: GET',
//     'Credentials: Basic asdasd5m9382dnn23ppasdkajgvkjmuneypp',
//     'Content: more-invalid-input',
//     'Method: POST',
//     'Credentials: Bearer asdkajgvkjmuneyppakfjhiaumdgh9nnqdppp',
//     'Content: invalid_input',
//     'Method: POST',
//     'Credentials: Basic asdasd5m9382dnn23ppasdasd5m9382dnn23pp',
//     'Content: and*more',
//     'Method: GET',
//     'Credentials: Bearer gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
//     'Content: someshit',
//     'Method: GET',
//     'Credentials: Bearer asdkajgvkjmuneyppasdasd5m9382dnn23pp',
//     'Content: watafak',
//     'Method: GET',
//     'Credentials: Basic asdasd5m9382dnn23ppasdasd5m9382dnn23pp',
//     'Content: 12398dsasd',
//     'Method: PUT',
//     'Credentials: Basic asdasd5m9382dnn23ppgkj39883m9278wenfyppp',
//     'Content: someshit',
//     'Method: GET',
//     'Credentials: Bearer asdasd5m9382dnn23ppasdasd5m9382dnn23pp',
//     'Content: Admin',
//     'Method: PUT',
//     'Credentials: Bearer gkj39883m9278wenfypppasdkajgvkjmuneypp',
//     'Content: televisionControll',
//     'Method: PUT',
//     'Credentials: Bearer gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
//     'Content: watafak',
//     'Method: DELETE',
//     'Credentials: Basic asdkajgvkjmuneyppakfjhiaumdgh9nnqdppp',
//     'Content: invalid_input',
//     'Method: DELETE',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppasdkajgvkjmuneypp',
//     'Content: televisionControll',
//     'Method: DELETE',
//     'Credentials: Basic gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
//     'Content: Spartaaaa',
//     'Method: PUT',
//     'Credentials: Basic asdkajgvkjmuneyppasdasd5m9382dnn23pp',
//     'Content: password',
//     'Method: GET',
//     'Credentials: Bearer gkj39883m9278wenfypppasdasd5m9382dnn23pp',
//     'Content: someshit',
//     'Method: GET',
//     'Credentials: Basic asdasd5m9382dnn23ppgkj39883m9278wenfyppp',
//     'Content: username',
//     'Method: PUT',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppasdasd5m9382dnn23pp',
//     'Content: this.is.sparta',
//     'Method: POST',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppasdasd5m9382dnn23pp',
//     'Content: invalid_input',
//     'Method: POST',
//     'Credentials: Basic asdasd5m9382dnn23ppakfjhiaumdgh9nnqdppp',
//     'Content: invalid_input',
//     'Method: DELETE',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppakfjhiaumdgh9nnqdppp',
//     'Content: someshit',
//     'Method: GET',
//     'Credentials: Bearer asdasd5m9382dnn23ppasdasd5m9382dnn23pp',
//     'Content: Admin',
//     'Method: PUT',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppakfjhiaumdgh9nnqdppp',
//     'Content: Admin',
//     'Method: DELETE',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppasdasd5m9382dnn23pp',
//     'Content: the.73l37U8135',
//     'Method: PUT',
//     'Credentials: Basic asdkajgvkjmuneyppasdasd5m9382dnn23pp',
//     'Content: Spartaaaa',
//     'Method: DELETE',
//     'Credentials: Basic gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
//     'Content: more-invalid-input',
//     'Method: PUT',
//     'Credentials: Basic gkj39883m9278wenfypppasdasd5m9382dnn23pp',
//     'Content: watafak',
//     'Method: PUT',
//     'Credentials: Basic asdkajgvkjmuneyppgkj39883m9278wenfyppp',
//     'Content: this.is.sparta',
//     'Method: GET',
//     'Credentials: Bearer asdasd5m9382dnn23ppgkj39883m9278wenfyppp',
//     'Content: 12398dsasd',
//     'Method: PUT',
//     'Credentials: Basic asdasd5m9382dnn23ppasdkajgvkjmuneypp',
//     'Content: password',
//     'Method: PUT',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppgkj39883m9278wenfyppp',
//     'Content: and*more',
//     'Method: DELETE',
//     'Credentials: Bearer asdkajgvkjmuneyppgkj39883m9278wenfyppp',
//     'Content: 12398dsasd',
//     'Method: POST',
//     'Credentials: Basic asdasd5m9382dnn23ppakfjhiaumdgh9nnqdppp',
//     'Content: televisionControll',
//     'Method: POST',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppakfjhiaumdgh9nnqdppp',
//     'Content: Spartaaaa',
//     'Method: PUT',
//     'Credentials: Basic gkj39883m9278wenfypppasdkajgvkjmuneypp',
//     'Content: 12398dsasd',
//     'Method: POST',
//     'Credentials: Basic asdasd5m9382dnn23ppakfjhiaumdgh9nnqdppp',
//     'Content: and*more',
//     'Method: GET',
//     'Credentials: Bearer asdasd5m9382dnn23ppasdkajgvkjmuneypp',
//     'Content: someshit',
//     'Method: POST',
//     'Credentials: Bearer asdkajgvkjmuneyppakfjhiaumdgh9nnqdppp',
//     'Content: invalid_input',
//     'Method: PUT',
//     'Credentials: Basic asdasd5m9382dnn23ppasdasd5m9382dnn23pp',
//     'Content: someshit',
//     'Method: GET',
//     'Credentials: Basic gkj39883m9278wenfypppgkj39883m9278wenfyppp',
//     'Content: password',
//     'Method: DELETE',
//     'Credentials: Basic gkj39883m9278wenfypppasdkajgvkjmuneypp',
//     'Content: username',
//     'Method: PUT',
//     'Credentials: Basic gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
//     'Content: more-invalid-input',
//     'Method: DELETE',
//     'Credentials: Bearer asdasd5m9382dnn23ppakfjhiaumdgh9nnqdppp',
//     'Content: invalid_input',
//     'Method: GET',
//     'Credentials: Basic gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
//     'Content: username',
//     'Method: POST',
//     'Credentials: Basic asdasd5m9382dnn23ppasdasd5m9382dnn23pp',
//     'Content: username',
//     'Method: POST',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppasdkajgvkjmuneypp',
//     'Content: 12398dsasd',
//     'Method: POST',
//     'Credentials: Bearer gkj39883m9278wenfypppasdkajgvkjmuneypp',
//     'Content: 12398dsasd',
//     'Method: GET',
//     'Credentials: Basic gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
//     'Content: someshit',
//     'Method: GET',
//     'Credentials: Basic gkj39883m9278wenfypppasdkajgvkjmuneypp',
//     'Content: 12398dsasd',
//     'Method: POST',
//     'Credentials: Basic asdasd5m9382dnn23ppasdkajgvkjmuneypp',
//     'Content: password',
//     'Method: PUT',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppasdkajgvkjmuneypp',
//     'Content: and*more',
//     'Method: PUT',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppasdasd5m9382dnn23pp',
//     'Content: someshit',
//     'Method: POST',
//     'Credentials: Bearer gkj39883m9278wenfypppgkj39883m9278wenfyppp',
//     'Content: someshit',
//     'Method: DELETE',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppakfjhiaumdgh9nnqdppp',
//     'Content: televisionControll',
//     'Method: DELETE',
//     'Credentials: Basic asdkajgvkjmuneyppgkj39883m9278wenfyppp',
//     'Content: username',
//     'Method: DELETE',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppakfjhiaumdgh9nnqdppp',
//     'Content: the.73l37U8135',
//     'Method: POST',
//     'Credentials: Basic asdkajgvkjmuneyppgkj39883m9278wenfyppp',
//     'Content: Admin',
//     'Method: GET',
//     'Credentials: Bearer asdkajgvkjmuneyppakfjhiaumdgh9nnqdppp',
//     'Content: invalid_input',
//     'Method: GET',
//     'Credentials: Bearer gkj39883m9278wenfypppasdkajgvkjmuneypp',
//     'Content: username',
//     'Method: GET',
//     'Credentials: Bearer asdkajgvkjmuneyppasdasd5m9382dnn23pp',
//     'Content: watafak',
//     'Method: GET',
//     'Credentials: Bearer asdasd5m9382dnn23ppakfjhiaumdgh9nnqdppp',
//     'Content: 12398dsasd',
//     'Method: DELETE',
//     'Credentials: Basic gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
//     'Content: username',
//     'Method: POST',
//     'Credentials: Bearer gkj39883m9278wenfypppasdasd5m9382dnn23pp',
//     'Content: and*more',
//     'Method: POST',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppakfjhiaumdgh9nnqdppp',
//     'Content: watafak',
//     'Method: POST',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppasdasd5m9382dnn23pp',
//     'Content: invalid_input',
//     'Method: PUT',
//     'Credentials: Basic asdkajgvkjmuneyppasdkajgvkjmuneypp',
//     'Content: 12398dsasd',
//     'Method: PUT',
//     'Credentials: Basic asdkajgvkjmuneyppgkj39883m9278wenfyppp',
//     'Content: invalid_input',
//     'Method: PUT',
//     'Credentials: Bearer asdkajgvkjmuneyppasdasd5m9382dnn23pp',
//     'Content: 12398dsasd',
//     'Method: PUT',
//     'Credentials: Basic asdasd5m9382dnn23ppgkj39883m9278wenfyppp',
//     'Content: Admin',
//     'Method: GET',
//     'Credentials: Basic asdasd5m9382dnn23ppakfjhiaumdgh9nnqdppp',
//     'Content: more-invalid-input',
//     'Method: POST',
//     'Credentials: Basic asdkajgvkjmuneyppgkj39883m9278wenfyppp',
//     'Content: username',
//     'Method: DELETE',
//     'Credentials: Bearer gkj39883m9278wenfypppasdasd5m9382dnn23pp',
//     'Content: Spartaaaa',
//     'Method: PUT',
//     'Credentials: Basic asdasd5m9382dnn23ppasdkajgvkjmuneypp',
//     'Content: more-invalid-input',
//     'Method: GET',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppgkj39883m9278wenfyppp',
//     'Content: username',
//     'Method: POST',
//     'Credentials: Basic asdkajgvkjmuneyppakfjhiaumdgh9nnqdppp',
//     'Content: Spartaaaa',
//     'Method: PUT',
//     'Credentials: Bearer asdkajgvkjmuneyppgkj39883m9278wenfyppp',
//     'Content: Admin',
//     'Method: PUT',
//     'Credentials: Bearer asdasd5m9382dnn23ppakfjhiaumdgh9nnqdppp',
//     'Content: the.73l37U8135',
//     'Method: PUT',
//     'Credentials: Basic asdkajgvkjmuneyppasdkajgvkjmuneypp',
//     'Content: invalid_input',
//     'Method: DELETE',
//     'Credentials: Bearer asdasd5m9382dnn23ppgkj39883m9278wenfyppp',
//     'Content: Spartaaaa',
//     'Method: PUT',
//     'Credentials: Basic asdkajgvkjmuneyppakfjhiaumdgh9nnqdppp',
//     'Content: and*more',
//     'Method: POST',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppasdasd5m9382dnn23pp',
//     'Content: Spartaaaa',
//     'Method: POST',
//     'Credentials: Bearer asdasd5m9382dnn23ppasdkajgvkjmuneypp',
//     'Content: password',
//     'Method: GET',
//     'Credentials: Basic asdasd5m9382dnn23ppakfjhiaumdgh9nnqdppp',
//     'Content: password',
//     'Method: PUT',
//     'Credentials: Bearer asdkajgvkjmuneyppasdkajgvkjmuneypp',
//     'Content: password',
//     'Method: PUT',
//     'Credentials: Basic asdkajgvkjmuneyppgkj39883m9278wenfyppp',
//     'Content: televisionControll',
//     'Method: DELETE',
//     'Credentials: Basic gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
//     'Content: username',
//     'Method: DELETE',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppasdkajgvkjmuneypp',
//     'Content: watafak',
//     'Method: POST',
//     'Credentials: Basic asdasd5m9382dnn23ppakfjhiaumdgh9nnqdppp',
//     'Content: someshit',
//     'Method: DELETE',
//     'Credentials: Bearer gkj39883m9278wenfypppasdkajgvkjmuneypp',
//     'Content: more-invalid-input',
//     'Method: GET',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppakfjhiaumdgh9nnqdppp',
//     'Content: invalid_input',
//     'Method: GET',
//     'Credentials: Basic gkj39883m9278wenfypppasdasd5m9382dnn23pp',
//     'Content: 12398dsasd',
//     'Method: PUT',
//     'Credentials: Bearer gkj39883m9278wenfypppgkj39883m9278wenfyppp',
//     'Content: Admin',
//     'Method: DELETE',
//     'Credentials: Basic asdkajgvkjmuneyppakfjhiaumdgh9nnqdppp',
//     'Content: password',
//     'Method: PUT',
//     'Credentials: Basic asdasd5m9382dnn23ppakfjhiaumdgh9nnqdppp',
//     'Content: someshit',
//     'Method: PUT',
//     'Credentials: Bearer gkj39883m9278wenfypppasdkajgvkjmuneypp',
//     'Content: more-invalid-input',
//     'Method: PUT',
//     'Credentials: Basic gkj39883m9278wenfypppgkj39883m9278wenfyppp',
//     'Content: password',
//     'Method: DELETE',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppasdkajgvkjmuneypp',
//     'Content: Spartaaaa',
//     'Method: DELETE',
//     'Credentials: Bearer asdkajgvkjmuneyppasdasd5m9382dnn23pp',
//     'Content: 12398dsasd',
//     'Method: PUT',
//     'Credentials: Bearer gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
//     'Content: this.is.sparta',
//     'Method: DELETE',
//     'Credentials: Bearer asdkajgvkjmuneyppasdasd5m9382dnn23pp',
//     'Content: Admin',
//     'Method: PUT',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppakfjhiaumdgh9nnqdppp',
//     'Content: invalid_input',
//     'Method: POST',
//     'Credentials: Bearer asdasd5m9382dnn23ppasdasd5m9382dnn23pp',
//     'Content: username',
//     'Method: GET',
//     'Credentials: Bearer asdasd5m9382dnn23ppasdasd5m9382dnn23pp',
//     'Content: and*more',
//     'Method: POST',
//     'Credentials: Bearer gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
//     'Content: Spartaaaa',
//     'Method: PUT',
//     'Credentials: Basic asdasd5m9382dnn23ppasdasd5m9382dnn23pp',
//     'Content: watafak',
//     'Method: DELETE',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppasdkajgvkjmuneypp',
//     'Content: password',
//     'Method: DELETE',
//     'Credentials: Basic asdasd5m9382dnn23ppasdasd5m9382dnn23pp',
//     'Content: Spartaaaa',
//     'Method: DELETE',
//     'Credentials: Basic gkj39883m9278wenfypppgkj39883m9278wenfyppp',
//     'Content: the.73l37U8135',
//     'Method: DELETE',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppasdkajgvkjmuneypp',
//     'Content: password',
//     'Method: PUT',
//     'Credentials: Bearer gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
//     'Content: televisionControll',
//     'Method: DELETE',
//     'Credentials: Basic asdasd5m9382dnn23ppasdkajgvkjmuneypp',
//     'Content: this.is.sparta',
//     'Method: GET',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppakfjhiaumdgh9nnqdppp',
//     'Content: username',
//     'Method: POST',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppgkj39883m9278wenfyppp',
//     'Content: 12398dsasd',
//     'Method: GET',
//     'Credentials: Basic asdkajgvkjmuneyppakfjhiaumdgh9nnqdppp',
//     'Content: someshit',
//     'Method: POST',
//     'Credentials: Bearer asdkajgvkjmuneyppasdasd5m9382dnn23pp',
//     'Content: and*more',
//     'Method: POST',
//     'Credentials: Basic asdasd5m9382dnn23ppasdasd5m9382dnn23pp',
//     'Content: Spartaaaa',
//     'Method: PUT',
//     'Credentials: Bearer asdkajgvkjmuneyppasdasd5m9382dnn23pp',
//     'Content: the.73l37U8135',
//     'Method: PUT',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppgkj39883m9278wenfyppp',
//     'Content: more-invalid-input',
//     'Method: POST',
//     'Credentials: Bearer gkj39883m9278wenfypppasdkajgvkjmuneypp',
//     'Content: invalid_input',
//     'Method: POST',
//     'Credentials: Basic asdkajgvkjmuneyppgkj39883m9278wenfyppp',
//     'Content: someshit',
//     'Method: POST',
//     'Credentials: Bearer asdkajgvkjmuneyppasdkajgvkjmuneypp',
//     'Content: more-invalid-input',
//     'Method: PUT',
//     'Credentials: Basic gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
//     'Content: someshit',
//     'Method: POST',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppakfjhiaumdgh9nnqdppp',
//     'Content: watafak',
//     'Method: GET',
//     'Credentials: Basic asdasd5m9382dnn23ppgkj39883m9278wenfyppp',
//     'Content: someshit',
//     'Method: DELETE',
//     'Credentials: Bearer asdasd5m9382dnn23ppasdkajgvkjmuneypp',
//     'Content: 12398dsasd',
//     'Method: POST',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppasdasd5m9382dnn23pp',
//     'Content: televisionControll',
//     'Method: PUT',
//     'Credentials: Basic asdkajgvkjmuneyppasdasd5m9382dnn23pp',
//     'Content: someshit',
//     'Method: DELETE',
//     'Credentials: Basic gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
//     'Content: invalid_input',
//     'Method: DELETE',
//     'Credentials: Basic asdkajgvkjmuneyppasdasd5m9382dnn23pp',
//     'Content: Spartaaaa',
//     'Method: GET',
//     'Credentials: Bearer asdkajgvkjmuneyppasdasd5m9382dnn23pp',
//     'Content: the.73l37U8135',
//     'Method: POST',
//     'Credentials: Bearer gkj39883m9278wenfypppgkj39883m9278wenfyppp',
//     'Content: Admin',
//     'Method: POST',
//     'Credentials: Bearer gkj39883m9278wenfypppasdasd5m9382dnn23pp',
//     'Content: Spartaaaa',
//     'Method: GET',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppasdasd5m9382dnn23pp',
//     'Content: someshit',
//     'Method: POST',
//     'Credentials: Basic asdasd5m9382dnn23ppasdkajgvkjmuneypp',
//     'Content: the.73l37U8135',
//     'Method: GET',
//     'Credentials: Basic asdasd5m9382dnn23ppasdkajgvkjmuneypp',
//     'Content: Admin',
//     'Method: PUT',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppasdasd5m9382dnn23pp',
//     'Content: the.73l37U8135',
//     'Method: PUT',
//     'Credentials: Basic asdkajgvkjmuneyppgkj39883m9278wenfyppp',
//     'Content: more-invalid-input',
//     'Method: POST',
//     'Credentials: Bearer asdkajgvkjmuneyppasdasd5m9382dnn23pp',
//     'Content: 12398dsasd',
//     'Method: DELETE',
//     'Credentials: Bearer asdasd5m9382dnn23ppasdasd5m9382dnn23pp',
//     'Content: username',
//     'Method: GET',
//     'Credentials: Bearer gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
//     'Content: televisionControll',
//     'Method: DELETE',
//     'Credentials: Basic gkj39883m9278wenfypppgkj39883m9278wenfyppp',
//     'Content: Admin',
//     'Method: GET',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppasdasd5m9382dnn23pp',
//     'Content: password',
//     'Method: PUT',
//     'Credentials: Bearer gkj39883m9278wenfypppgkj39883m9278wenfyppp',
//     'Content: televisionControll',
//     'Method: DELETE',
//     'Credentials: Basic gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
//     'Content: password',
//     'Method: GET',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppasdasd5m9382dnn23pp',
//     'Content: username',
//     'Method: POST',
//     'Credentials: Bearer asdasd5m9382dnn23ppasdasd5m9382dnn23pp',
//     'Content: this.is.sparta',
//     'Method: POST',
//     'Credentials: Basic gkj39883m9278wenfypppasdasd5m9382dnn23pp',
//     'Content: someshit',
//     'Method: PUT',
//     'Credentials: Basic asdasd5m9382dnn23ppgkj39883m9278wenfyppp',
//     'Content: televisionControll',
//     'Method: GET',
//     'Credentials: Basic asdkajgvkjmuneyppgkj39883m9278wenfyppp',
//     'Content: invalid_input',
//     'Method: DELETE',
//     'Credentials: Basic asdkajgvkjmuneyppakfjhiaumdgh9nnqdppp',
//     'Content: invalid_input',
//     'Method: POST',
//     'Credentials: Basic gkj39883m9278wenfypppasdkajgvkjmuneypp',
//     'Content: this.is.sparta',
//     'Method: POST',
//     'Credentials: Bearer asdasd5m9382dnn23ppasdasd5m9382dnn23pp',
//     'Content: televisionControll',
//     'Method: DELETE',
//     'Credentials: Basic asdasd5m9382dnn23ppasdkajgvkjmuneypp',
//     'Content: televisionControll',
//     'Method: GET',
//     'Credentials: Bearer gkj39883m9278wenfypppgkj39883m9278wenfyppp',
//     'Content: more-invalid-input',
//     '2m5p3n']);

// ajaxRequestValidator([
//     'Method: PUT',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppasdasd5m9382dnn23pp',
//     'Content: Admin',
//     'Method: DELETE',
//     'Credentials: Bearer gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
//     'Content: the.73l37U8135',
//     'Method: DELETE',
//     'Credentials: Basic asdasd5m9382dnn23ppasdkajgvkjmuneypp',
//     'Content: invalid_input',
//     'Method: DELETE',
//     'Credentials: Basic asdkajgvkjmuneyppasdasd5m9382dnn23pp',
//     'Content: and*more',
//     'Method: POST',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppasdkajgvkjmuneypp',
//     'Content: username',
//     'Method: POST',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppasdasd5m9382dnn23pp',
//     'Content: and*more',
//     'Method: GET',
//     'Credentials: Basic asdkajgvkjmuneyppgkj39883m9278wenfyppp',
//     'Content: this.is.sparta',
//     'Method: GET',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppasdkajgvkjmuneypp',
//     'Content: password',
//     'Method: GET',
//     'Credentials: Basic asdasd5m9382dnn23ppasdasd5m9382dnn23pp',
//     'Content: someshit',
//     'Method: DELETE',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppasdkajgvkjmuneypp',
//     'Content: invalid_input',
//     'Method: PUT',
//     'Credentials: Bearer gkj39883m9278wenfypppasdkajgvkjmuneypp',
//     'Content: 12398dsasd',
//     'Method: POST',
//     'Credentials: Basic asdkajgvkjmuneyppasdkajgvkjmuneypp',
//     'Content: more-invalid-input',
//     'Method: DELETE',
//     'Credentials: Bearer asdkajgvkjmuneyppgkj39883m9278wenfyppp',
//     'Content: password',
//     'Method: DELETE',
//     'Credentials: Bearer asdkajgvkjmuneyppgkj39883m9278wenfyppp',
//     'Content: password',
//     'Method: GET',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppgkj39883m9278wenfyppp',
//     'Content: more-invalid-input',
//     'Method: PUT',
//     'Credentials: Bearer gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
//     'Content: more-invalid-input',
//     'Method: GET',
//     'Credentials: Bearer asdkajgvkjmuneyppasdasd5m9382dnn23pp',
//     'Content: televisionControll',
//     'Method: POST',
//     'Credentials: Basic asdasd5m9382dnn23ppasdasd5m9382dnn23pp',
//     'Content: watafak',
//     'Method: POST',
//     'Credentials: Basic gkj39883m9278wenfypppgkj39883m9278wenfyppp',
//     'Content: televisionControll',
//     'Method: GET',
//     'Credentials: Bearer asdkajgvkjmuneyppasdkajgvkjmuneypp',
//     'Content: someshit',
//     'Method: POST',
//     'Credentials: Bearer asdkajgvkjmuneyppasdkajgvkjmuneypp',
//     'Content: Spartaaaa',
//     'Method: POST',
//     'Credentials: Bearer asdasd5m9382dnn23ppasdkajgvkjmuneypp',
//     'Content: and*more',
//     'Method: DELETE',
//     'Credentials: Basic gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
//     'Content: the.73l37U8135',
//     'Method: PUT',
//     'Credentials: Basic asdasd5m9382dnn23ppasdasd5m9382dnn23pp',
//     'Content: the.73l37U8135',
//     'Method: DELETE',
//     'Credentials: Bearer gkj39883m9278wenfypppasdkajgvkjmuneypp',
//     'Content: more-invalid-input',
//     'Method: GET',
//     'Credentials: Basic gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
//     'Content: the.73l37U8135',
//     'Method: POST',
//     'Credentials: Bearer asdkajgvkjmuneyppasdasd5m9382dnn23pp',
//     'Content: the.73l37U8135',
//     'Method: DELETE',
//     'Credentials: Basic asdasd5m9382dnn23ppasdkajgvkjmuneypp',
//     'Content: Admin',
//     'Method: DELETE',
//     'Credentials: Bearer gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
//     'Content: someshit',
//     'Method: PUT',
//     'Credentials: Bearer gkj39883m9278wenfypppasdasd5m9382dnn23pp',
//     'Content: more-invalid-input',
//     'Method: GET',
//     'Credentials: Bearer gkj39883m9278wenfypppasdkajgvkjmuneypp',
//     'Content: and*more',
//     'Method: GET',
//     'Credentials: Bearer asdasd5m9382dnn23ppakfjhiaumdgh9nnqdppp',
//     'Content: more-invalid-input',
//     'Method: POST',
//     'Credentials: Bearer gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
//     'Content: more-invalid-input',
//     'Method: PUT',
//     'Credentials: Bearer gkj39883m9278wenfypppgkj39883m9278wenfyppp',
//     'Content: Spartaaaa',
//     'Method: DELETE',
//     'Credentials: Basic gkj39883m9278wenfypppasdkajgvkjmuneypp',
//     'Content: and*more',
//     'Method: PUT',
//     'Credentials: Bearer asdasd5m9382dnn23ppasdkajgvkjmuneypp',
//     'Content: Admin',
//     'Method: POST',
//     'Credentials: Basic asdkajgvkjmuneyppgkj39883m9278wenfyppp',
//     'Content: Spartaaaa',
//     'Method: GET',
//     'Credentials: Bearer asdkajgvkjmuneyppasdkajgvkjmuneypp',
//     'Content: watafak',
//     'Method: PUT',
//     'Credentials: Basic asdkajgvkjmuneyppakfjhiaumdgh9nnqdppp',
//     'Content: Admin',
//     'Method: POST',
//     'Credentials: Basic asdasd5m9382dnn23ppgkj39883m9278wenfyppp',
//     'Content: Admin',
//     'Method: POST',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppasdasd5m9382dnn23pp',
//     'Content: someshit',
//     'Method: PUT',
//     'Credentials: Basic gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
//     'Content: this.is.sparta',
//     'Method: PUT',
//     'Credentials: Bearer asdkajgvkjmuneyppasdkajgvkjmuneypp',
//     'Content: Admin',
//     'Method: DELETE',
//     'Credentials: Bearer gkj39883m9278wenfypppgkj39883m9278wenfyppp',
//     'Content: more-invalid-input',
//     'Method: GET',
//     'Credentials: Basic gkj39883m9278wenfypppasdasd5m9382dnn23pp',
//     'Content: televisionControll',
//     'Method: PUT',
//     'Credentials: Basic asdkajgvkjmuneyppakfjhiaumdgh9nnqdppp',
//     'Content: 12398dsasd',
//     'Method: DELETE',
//     'Credentials: Bearer asdasd5m9382dnn23ppgkj39883m9278wenfyppp',
//     'Content: invalid_input',
//     'Method: PUT',
//     'Credentials: Basic gkj39883m9278wenfypppasdkajgvkjmuneypp',
//     'Content: and*more',
//     'Method: PUT',
//     'Credentials: Basic gkj39883m9278wenfypppasdasd5m9382dnn23pp',
//     'Content: password',
//     'Method: POST',
//     'Credentials: Bearer gkj39883m9278wenfypppasdasd5m9382dnn23pp',
//     'Content: watafak',
//     'Method: PUT',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppasdkajgvkjmuneypp',
//     'Content: and*more',
//     'Method: PUT',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppakfjhiaumdgh9nnqdppp',
//     'Content: watafak',
//     'Method: PUT',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppgkj39883m9278wenfyppp',
//     'Content: someshit',
//     'Method: PUT',
//     'Credentials: Bearer gkj39883m9278wenfypppasdkajgvkjmuneypp',
//     'Content: this.is.sparta',
//     'Method: PUT',
//     'Credentials: Bearer asdkajgvkjmuneyppgkj39883m9278wenfyppp',
//     'Content: the.73l37U8135',
//     'Method: PUT',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppasdasd5m9382dnn23pp',
//     'Content: more-invalid-input',
//     'Method: GET',
//     'Credentials: Bearer gkj39883m9278wenfypppasdkajgvkjmuneypp',
//     'Content: and*more',
//     'Method: PUT',
//     'Credentials: Basic gkj39883m9278wenfypppasdasd5m9382dnn23pp',
//     'Content: Admin',
//     'Method: POST',
//     'Credentials: Bearer asdkajgvkjmuneyppasdasd5m9382dnn23pp',
//     'Content: username',
//     'Method: DELETE',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppgkj39883m9278wenfyppp',
//     'Content: Spartaaaa',
//     'Method: POST',
//     'Credentials: Bearer asdasd5m9382dnn23ppasdkajgvkjmuneypp',
//     'Content: the.73l37U8135',
//     'Method: DELETE',
//     'Credentials: Bearer gkj39883m9278wenfypppasdasd5m9382dnn23pp',
//     'Content: username',
//     'Method: PUT',
//     'Credentials: Bearer asdkajgvkjmuneyppasdasd5m9382dnn23pp',
//     'Content: 12398dsasd',
//     'Method: POST',
//     'Credentials: Basic asdasd5m9382dnn23ppgkj39883m9278wenfyppp',
//     'Content: watafak',
//     'Method: PUT',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppgkj39883m9278wenfyppp',
//     'Content: the.73l37U8135',
//     'Method: PUT',
//     'Credentials: Bearer asdasd5m9382dnn23ppasdasd5m9382dnn23pp',
//     'Content: Admin',
//     'Method: DELETE',
//     'Credentials: Bearer asdasd5m9382dnn23ppgkj39883m9278wenfyppp',
//     'Content: 12398dsasd',
//     'Method: DELETE',
//     'Credentials: Basic asdkajgvkjmuneyppasdkajgvkjmuneypp',
//     'Content: the.73l37U8135',
//     'Method: POST',
//     'Credentials: Basic asdasd5m9382dnn23ppgkj39883m9278wenfyppp',
//     'Content: someshit',
//     'Method: DELETE',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppgkj39883m9278wenfyppp',
//     'Content: invalid_input',
//     'Method: PUT',
//     'Credentials: Basic gkj39883m9278wenfypppasdasd5m9382dnn23pp',
//     'Content: username',
//     'Method: GET',
//     'Credentials: Basic asdkajgvkjmuneyppasdasd5m9382dnn23pp',
//     'Content: more-invalid-input',
//     'Method: GET',
//     'Credentials: Bearer gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
//     'Content: 12398dsasd',
//     'Method: POST',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppasdkajgvkjmuneypp',
//     'Content: more-invalid-input',
//     'Method: DELETE',
//     'Credentials: Basic asdkajgvkjmuneyppakfjhiaumdgh9nnqdppp',
//     'Content: someshit',
//     'Method: GET',
//     'Credentials: Basic asdasd5m9382dnn23ppgkj39883m9278wenfyppp',
//     'Content: invalid_input',
//     'Method: DELETE',
//     'Credentials: Basic asdasd5m9382dnn23ppgkj39883m9278wenfyppp',
//     'Content: watafak',
//     'Method: PUT',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppakfjhiaumdgh9nnqdppp',
//     'Content: watafak',
//     'Method: PUT',
//     'Credentials: Basic asdkajgvkjmuneyppasdkajgvkjmuneypp',
//     'Content: invalid_input',
//     'Method: GET',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppasdasd5m9382dnn23pp',
//     'Content: televisionControll',
//     'Method: PUT',
//     'Credentials: Basic asdasd5m9382dnn23ppakfjhiaumdgh9nnqdppp',
//     'Content: this.is.sparta',
//     'Method: POST',
//     'Credentials: Basic asdasd5m9382dnn23ppakfjhiaumdgh9nnqdppp',
//     'Content: 12398dsasd',
//     'Method: PUT',
//     'Credentials: Basic asdkajgvkjmuneyppakfjhiaumdgh9nnqdppp',
//     'Content: username',
//     'Method: PUT',
//     'Credentials: Bearer asdkajgvkjmuneyppgkj39883m9278wenfyppp',
//     'Content: Admin',
//     'Method: PUT',
//     'Credentials: Bearer asdasd5m9382dnn23ppasdasd5m9382dnn23pp',
//     'Content: someshit',
//     'Method: PUT',
//     'Credentials: Basic gkj39883m9278wenfypppasdasd5m9382dnn23pp',
//     'Content: and*more',
//     'Method: POST',
//     'Credentials: Bearer asdkajgvkjmuneyppasdasd5m9382dnn23pp',
//     'Content: invalid_input',
//     'Method: POST',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppasdkajgvkjmuneypp',
//     'Content: the.73l37U8135',
//     'Method: DELETE',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppasdkajgvkjmuneypp',
//     'Content: Spartaaaa',
//     'Method: POST',
//     'Credentials: Bearer gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
//     'Content: username',
//     'Method: PUT',
//     'Credentials: Bearer akfjhiaumdgh9nnqdpppasdkajgvkjmuneypp',
//     'Content: and*more',
//     'Method: PUT',
//     'Credentials: Bearer asdasd5m9382dnn23ppasdkajgvkjmuneypp',
//     'Content: watafak',
//     'Method: GET',
//     'Credentials: Bearer asdasd5m9382dnn23ppakfjhiaumdgh9nnqdppp',
//     'Content: and*more',
//     'Method: POST',
//     'Credentials: Basic asdkajgvkjmuneyppakfjhiaumdgh9nnqdppp',
//     'Content: password',
//     'Method: POST',
//     'Credentials: Basic asdasd5m9382dnn23ppasdasd5m9382dnn23pp',
//     'Content: 12398dsasd',
//     'Method: GET',
//     'Credentials: Basic asdasd5m9382dnn23ppgkj39883m9278wenfyppp',
//     'Content: username',
//     'Method: DELETE',
//     'Credentials: Basic gkj39883m9278wenfypppasdasd5m9382dnn23pp',
//     'Content: invalid_input',
//     'Method: GET',
//     'Credentials: Bearer asdkajgvkjmuneyppasdkajgvkjmuneypp',
//     'Content: Spartaaaa',
//     'Method: DELETE',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppasdkajgvkjmuneypp',
//     'Content: 12398dsasd',
//     'Method: PUT',
//     'Credentials: Basic gkj39883m9278wenfypppgkj39883m9278wenfyppp',
//     'Content: Admin',
//     'Method: DELETE',
//     'Credentials: Bearer asdkajgvkjmuneyppasdasd5m9382dnn23pp',
//     'Content: username',
//     'Method: PUT',
//     'Credentials: Bearer asdasd5m9382dnn23ppgkj39883m9278wenfyppp',
//     'Content: and*more',
//     'Method: GET',
//     'Credentials: Bearer asdasd5m9382dnn23ppakfjhiaumdgh9nnqdppp',
//     'Content: Spartaaaa',
//     'Method: DELETE',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppgkj39883m9278wenfyppp',
//     'Content: invalid_input',
//     'Method: GET',
//     'Credentials: Bearer asdasd5m9382dnn23ppasdkajgvkjmuneypp',
//     'Content: and*more',
//     'Method: GET',
//     'Credentials: Basic gkj39883m9278wenfypppakfjhiaumdgh9nnqdppp',
//     'Content: watafak',
//     'Method: PUT',
//     'Credentials: Basic asdasd5m9382dnn23ppasdkajgvkjmuneypp',
//     'Content: watafak',
//     'Method: DELETE',
//     'Credentials: Basic asdkajgvkjmuneyppasdasd5m9382dnn23pp',
//     'Content: someshit',
//     'Method: PUT',
//     'Credentials: Basic gkj39883m9278wenfypppasdasd5m9382dnn23pp',
//     'Content: invalid_input',
//     'Method: GET',
//     'Credentials: Bearer gkj39883m9278wenfypppgkj39883m9278wenfyppp',
//     'Content: the.73l37U8135',
//     'Method: PUT',
//     'Credentials: Basic asdkajgvkjmuneyppasdasd5m9382dnn23pp',
//     'Content: password',
//     'Method: GET',
//     'Credentials: Bearer asdkajgvkjmuneyppasdasd5m9382dnn23pp',
//     'Content: televisionControll',
//     'Method: PUT',
//     'Credentials: Basic asdasd5m9382dnn23ppasdasd5m9382dnn23pp',
//     'Content: televisionControll',
//     'Method: DELETE',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppgkj39883m9278wenfyppp',
//     'Content: and*more',
//     'Method: DELETE',
//     'Credentials: Bearer gkj39883m9278wenfypppasdasd5m9382dnn23pp',
//     'Content: invalid_input',
//     'Method: POST',
//     'Credentials: Basic akfjhiaumdgh9nnqdpppasdasd5m9382dnn23pp',
//     'Content: password',
//     'Method: PUT',
//     'Credentials: Bearer asdasd5m9382dnn23ppakfjhiaumdgh9nnqdppp',
//     'Content: 12398dsasd',
//     'Method: GET',
//     'Credentials: Basic asdkajgvkjmuneyppgkj39883m9278wenfyppp',
//     'Content: watafak',
//     'Method: DELETE',
//     'Credentials: Bearer gkj39883m9278wenfypppasdkajgvkjmuneypp',
//     'Content: televisionControll',
//     'Method: POST',
//     'Credentials: Basic gkj39883m9278wenfypppasdkajgvkjmuneypp',
//     'Content: password',
//     '2m5p3n'
// ]);


// ajaxRequestValidator([
// 'Method: GET',
// 'Credentials: Bearer asd918721jsdbhjslkfwkiuwjoxXJIdahefJAB',
// 'Content: users.asd.1782452.278asd',
// 'Method: POST',
// 'Credentials: Basic 028591u3jtndkgwndsdkfjwelfkjwporjebhas',
// 'Content: Johnathan',
// '0q'
// ]);
//
// console.log('\n---\n');
//
// ajaxRequestValidator(['Method: PUT',
//     'Credentials: Bearer as9133jsdbhjslkfqwkqiuwjoxXJIdahefJAB',
//     'Content: users.asd/1782452$278///**asd123',
//     'Method: POST',
//     'Credentials: Bearer 028591u3jtndkgwndskfjwelfqkjwporjqebhas',
//     'Content: Johnathan',
//     'Method: DELETE',
//     'Credentials: Bearer 05366u3jtndkgwndssfsfgeryerrrrrryjihvx',
//     'Content: This.is.a.sample.content',
//     '2e5g'
// ]);